config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  resources :trainers
  resources :clients

  post 'clients/find' => 'clients#find'
  post 'trainers/find' => 'trainers#find'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :workouts
	has_many :trainers, :through => :workouts
end

app/models/trainer.rb
class Trainer < ApplicationRecord
	has_many :workouts
	has_many :clients, :through => :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
	belongs_to :client
	belongs_to :trainer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  def find
    puts params[:search_string]
    @results = Client.where(name: params[:search_string])
  end


  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :address, :current_weight, :height, :gender, :email_add)
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  def find
    puts params[:search_string]
    @results = Trainer.where(name: params[:search_string])
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :address, :current_weight, :height, :gender, :email_add)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:client_id, :trainer_id, :duration_mins, :date_of_workout, :paid_amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :current_weight %>
    <%= form.text_field :current_weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :email_add %>
    <%= form.text_field :email_add %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/find.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag "/clients/find" do %>
    <%= text_field_tag :search_string %>
    <%= submit_tag :search %>
    <% end %>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Current weight</th>
      <th>Height</th>
      <th>Gender</th>
      <th>Email add</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.address %></td>
        <td><%= client.current_weight %></td>
        <td><%= client.height %></td>
        <td><%= client.gender %></td>
        <td><%= client.email_add %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag "/clients/find" do %>
    <%= text_field_tag :search_string %>
    <%= submit_tag :search %>
    <% end %>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Current weight</th>
      <th>Height</th>
      <th>Gender</th>
      <th>Email add</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.address %></td>
        <td><%= client.current_weight %></td>
        <td><%= client.height %></td>
        <td><%= client.gender %></td>
        <td><%= client.email_add %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Current weight:</strong>
  <%= @client.current_weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @client.height %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @client.gender %>
</p>

<p>
  <strong>Email add:</strong>
  <%= @client.email_add %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientWorkouts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/trainers/_form.html.erb
<%= form_with(model: trainer, local: true) do |form| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :current_weight %>
    <%= form.text_field :current_weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :email_add %>
    <%= form.text_field :email_add %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/find.html.erb
<p id="notice"><%= notice %></p>

    <%= form_tag "/trainers/find" do %>
    <%= text_field_tag :search_string %>
    <%= submit_tag :search %>
    <% end %>

<h1>Trainers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Current weight</th>
      <th>Height</th>
      <th>Gender</th>
      <th>Email add</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |trainer| %>
      <tr>
        <td><%= trainer.name %></td>
        <td><%= trainer.address %></td>
        <td><%= trainer.current_weight %></td>
        <td><%= trainer.height %></td>
        <td><%= trainer.gender %></td>
        <td><%= trainer.email_add %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

    <%= form_tag "/trainers/find" do %>
    <%= text_field_tag :search_string %>
    <%= submit_tag :search %>
    <% end %>

<h1>Trainers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Current weight</th>
      <th>Height</th>
      <th>Gender</th>
      <th>Email add</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.name %></td>
        <td><%= trainer.address %></td>
        <td><%= trainer.current_weight %></td>
        <td><%= trainer.height %></td>
        <td><%= trainer.gender %></td>
        <td><%= trainer.email_add %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @trainer.address %>
</p>

<p>
  <strong>Current weight:</strong>
  <%= @trainer.current_weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @trainer.height %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @trainer.gender %>
</p>

<p>
  <strong>Email add:</strong>
  <%= @trainer.email_add %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>

app/views/workouts/_form.html.erb
<%= form_with(model: workout, local: true) do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select(:client_id, Client.all, :id, :name, :prompt => 'Select Client') %>
  </div>

  <div class="field">
    <%= form.label :trainer_id %>
    <%= form.collection_select(:trainer_id, Trainer.all, :id, :name, :prompt => 'Select Trainer') %>
  </div>

  <div class="field">
    <%= form.label :duration_mins %>
    <%= form.number_field :duration_mins %>
  </div>

  <div class="field">
    <%= form.label :date_of_workout %>
    <%= form.date_select :date_of_workout %>
  </div>

  <div class="field">
    <%= form.label :paid_amount %>
    <%= form.text_field :paid_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/find.html.erb
<p id="notice"><%= notice %></p>

<h1>Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Trainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |workout| %>
      <tr>
        <td><%= workout.client_name %></td>
        <td><%= workout.trainer %></td>
        <td><%= workout.duration_mins %></td>
        <td><%= workout.date_of_workout %></td>
        <td><%= workout.paid_amount %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Trainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><a href="http://localhost:3000/clients/<%= workout.client.id %>"><%= workout.client.name %></a></td>
        <td><a href="http://localhost:3000/trainers/<%= workout.trainer.id %>"><%= workout.trainer.name %></a></td>
        <td><%= workout.duration_mins %></td>
        <td><%= workout.date_of_workout %></td>
        <td><%= workout.paid_amount %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @workout.client_id %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @workout.trainer_id %>
</p>

<p>
  <strong>Duration mins:</strong>
  <%= @workout.duration_mins %>
</p>

<p>
  <strong>Date of workout:</strong>
  <%= @workout.date_of_workout %>
</p>

<p>
  <strong>Paid amount:</strong>
  <%= @workout.paid_amount %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>